spring.application.name=LetsPlayAPI
spring.data.mongodb.uri=mongodb+srv://denilany1_db_user:dgMx2s0OwFBGA8kv@bootleaf.ffga69i.mongodb.net/letsplaydb?retryWrites=true&w=majority&appName=BootLeaf

jwt.secret=your_very_long_and_very_secret_random_string_here_1234567890
jwt.expiration=86400000